#!/bin/sh
reldir=`dirname $0`
exec python $reldir/lib/python/ZEO/start.py \
  -U $reldir/var/zeo.soc \
  ZEO_SERVER_PID=$reldir/var/ZEO_SERVER.pid \
  STUPID_LOG_FILE=$reldir/var/ZEO_EVENTS.log \
  "$@" 

